{{/*
Copyright © 2018 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: BSD-2-Clause
*/}}
{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "fluentd-router.labels" . | nindent 4 }}
  name: {{ template "fluentd-router.fullname" . }}
  {{- if .Values.rbac.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.rbac.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{ if .Values.imagePullSecret }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecret}}
{{end}}
{{- end }}
