{{/*
Copyright © 2018 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: BSD-2-Clause
*/}}
{{- if .Values.prometheusEnabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "fluentd-router.labels" . | nindent 4 }}
    metrics: fluentd
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "24231"
  name: {{ template "fluentd-router.fullname" . }}
spec:
  selector:
    {{- include "fluentd-router.selectorLabels" . | nindent 4 }}
  ports:
    - port: 24231
      name: prometheus
      targetPort: prometheus

---

apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "fluentd-router.labels" . | nindent 4 }}
    metrics: reloader
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.metricsPort | quote }}
  name: {{ template "fluentd-router.fullname" . }}-reloader
spec:
  selector:
    {{- include "fluentd-router.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.metricsPort }}
      name: metrics
      targetPort: metrics
{{- end }}
