{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "fluentd-router.fullname" . }}
  labels:
    {{- include "fluentd-router.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: {{ .Values.serviceMonitor.jobLabel | quote }}
  selector:
    matchLabels:
      {{- include "fluentd-router.selectorLabels" . | nindent 6 }}
      metrics: fluentd
  endpoints:
  - port: prometheus
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "fluentd-router.fullname" . }}-reloader
  labels:
    {{- include "fluentd-router.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: {{ .Values.serviceMonitor.jobLabel | quote }}
  selector:
    matchLabels:
      {{- include "fluentd-router.selectorLabels" . | nindent 6 }}
      metrics: reloader
  endpoints:
  - port: metrics
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
{{- end }}
