{{/*
Copyright © 2018 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: BSD-2-Clause
*/}}
{{- $root := . -}}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fluentd-router.fullname" . }}
  labels:
    app: {{ template "fluentd-router.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "fluentd-router.name" . }}
        release: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "fluentd-router.fullname" . }}{{ else }}"{{ .Values.serviceAccountName }}"{{ end }}
      containers:
        - name: fluentd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ template "fluentd-router.fullname" $root }}
                key: {{ $key }}
        {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.prometheusEnabled }}
          ports:
          - name: prometheus
            containerPort: 24231
          {{- end }}
          volumeMounts:
          - name: fluentconf
            mountPath: /fluentd/etc
          - name: varlog
            mountPath: /var/log
          - name: kubeletroot
            mountPath: "{{ .Values.kubeletRoot }}"
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 10 }}
{{- end }}
          resources:
{{ toYaml .Values.fluentdResources | indent 12 }}

        - name: reloader
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          -  /bin/config-reloader
          - --interval={{ .Values.interval }}
          - --log-level={{ .Values.logLevel }}
          - --output-dir=/fluentd/etc
          - --templates-dir=/templates
          - --id={{ template "fluentd-router.fullname" . }}
          - --fluentd-binary
          - /usr/local/bin/fluentd -p /fluentd/plugins
          - --kubelet-root
          - "{{ .Values.kubeletRoot }}"
          {{- if .Values.meta.key }}
          - --meta-key={{ .Values.meta.key }}
          - --meta-values={{- range $k, $v := .Values.meta.values }}{{$k}}={{$v}},
          {{- end }}
          {{- end }}
          {{- if .Values.prometheusEnabled }}
          - --prometheus-enabled
          {{- end }}
          {{- range  .Values.namespaces }}
          - --namespaces
          - "{{ . }}"
          {{- end }}
          volumeMounts:
          - name: fluentconf
            mountPath: /fluentd/etc
          resources:
{{ toYaml .Values.reloaderResources | indent 12 }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end}}
      volumes:
      - name: fluentconf
        emptyDir: {}
      - name: kubeletroot
        hostPath:
          path: "{{ .Values.kubeletRoot }}"
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
  {{- if .Values.updateStrategy}}
  updateStrategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  {{- end }}
