/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/vmware/kube-fluentd-operator/config-reloader/datasource/kubedatasource/fluentdconfig/apis/logs.vdp.vmware.com/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFluentdConfigs implements FluentdConfigInterface
type FakeFluentdConfigs struct {
	Fake *FakeLogsV1beta1
	ns   string
}

var fluentdconfigsResource = schema.GroupVersionResource{Group: "logs.vdp.vmware.com", Version: "v1beta1", Resource: "fluentdconfigs"}

var fluentdconfigsKind = schema.GroupVersionKind{Group: "logs.vdp.vmware.com", Version: "v1beta1", Kind: "FluentdConfig"}

// Get takes name of the fluentdConfig, and returns the corresponding fluentdConfig object, and an error if there is any.
func (c *FakeFluentdConfigs) Get(name string, options v1.GetOptions) (result *v1beta1.FluentdConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(fluentdconfigsResource, c.ns, name), &v1beta1.FluentdConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FluentdConfig), err
}

// List takes label and field selectors, and returns the list of FluentdConfigs that match those selectors.
func (c *FakeFluentdConfigs) List(opts v1.ListOptions) (result *v1beta1.FluentdConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(fluentdconfigsResource, fluentdconfigsKind, c.ns, opts), &v1beta1.FluentdConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.FluentdConfigList{ListMeta: obj.(*v1beta1.FluentdConfigList).ListMeta}
	for _, item := range obj.(*v1beta1.FluentdConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fluentdConfigs.
func (c *FakeFluentdConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(fluentdconfigsResource, c.ns, opts))

}

// Create takes the representation of a fluentdConfig and creates it.  Returns the server's representation of the fluentdConfig, and an error, if there is any.
func (c *FakeFluentdConfigs) Create(fluentdConfig *v1beta1.FluentdConfig) (result *v1beta1.FluentdConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(fluentdconfigsResource, c.ns, fluentdConfig), &v1beta1.FluentdConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FluentdConfig), err
}

// Update takes the representation of a fluentdConfig and updates it. Returns the server's representation of the fluentdConfig, and an error, if there is any.
func (c *FakeFluentdConfigs) Update(fluentdConfig *v1beta1.FluentdConfig) (result *v1beta1.FluentdConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(fluentdconfigsResource, c.ns, fluentdConfig), &v1beta1.FluentdConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FluentdConfig), err
}

// Delete takes name of the fluentdConfig and deletes it. Returns an error if one occurs.
func (c *FakeFluentdConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(fluentdconfigsResource, c.ns, name), &v1beta1.FluentdConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFluentdConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(fluentdconfigsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.FluentdConfigList{})
	return err
}

// Patch applies the patch and returns the patched fluentdConfig.
func (c *FakeFluentdConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.FluentdConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(fluentdconfigsResource, c.ns, name, pt, data, subresources...), &v1beta1.FluentdConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.FluentdConfig), err
}
